shared: &shared
  site_name: Square Roots
  from_email: info@squareroots.com
  info_email: info@squareroots.com
  meta_keywords: 'redefining,health,at,the,foundation,of,life,square,roots'
  meta_description: "Square Roots: Redefining health at the foundation of life."

development:
  <<: *shared
  secret_key_base: 0f6d22b4224b1be66e528e742b6ac8f1100b4dbcd766008fb6d42e6e8e165673bd68d452aa7fc98ea4e238ff43be737a6759301c9d22f2a5c663848f23bdd7e2

test:
  <<: *shared
  secret_key_base: 56edc9eb06664a812c023e189db20c47cf66c2d23aeedc4a23b76182a8cd1464461f7a33c1a687c404f91407ffb2d350920102d11355832f736cb816a137c532

production:
  <<: *shared
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  <<: *shared
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
